const initialState = `Aktium Savaşı Marcus Antonius ve Kleopatra'nın yenilgisiyle sonuçlanmış ve her ikisi de savaşın ardından intihar etmişti. Octavianus, Kleopatra'nın oğlu ve eş-yönetici Caesarion'u öldürtmüştü. Ceasarion, muhtemelen Jül Sezar'ın tek oğluydu. Dolayısıyla Caesarion'u öldürerek Octavianus, Jül Sezar ile yakın kan bağı bulunan herhangi bir erkek rakip olasılığını da ortadan kaldırmış oldu. Roma'nın tek ve yegane yöneticisi olan Octavianus askerî, malî ve siyasi meselelerin tam kapsamlı bir onarımına girişti. Bu girişimler Roma dünyasını istikrara oturtmayı ve pasifize etmeyi, aynı zamanda da yeni rejimin kabul görmesini sağlamayı amaçlıyordu.
Octavianus'un Roma aleminin yöneticisi olmasının ardından Roma senatosu kendisine Augustus ismini verdi. Bu sırada ilk adı olarak imperator (Baş komutan) unvanını zaten kullanmaktaydı. Bu cumhuriyet döneminden beri kullanılan bir unvandı.
Sezar'ın evlatlık vârisi olan Augustus, Sezar adıyla çağrılmayı tercih etmişti. Sezar aile adının bir parçasıydı. Julio-Claudian yönetimi yaklaşık bir asır sürdü (MÖ 1. yüzyılın ortalarında Jül Sezar'ın iktidara gelmesinden 1. yüzyıl ortalarında imparator Nero'ya kadar). Flavius hanedanı döneminde ve Vespasianus ve oğulları Titus ve Domitianus'un hükümdarlığında Sezar kavramı fiiliyatta bir aile isminden resmî bir unvana dönüşmüştü. Çar, kayzer ve şah gibi bu unvanın türevleri bugüne kadar gelmiştir.
İç savaşlar yüzünden o güne kadar rastlanmamış sayılara ulaşan (50 civarında) Roma lejyonlarının sayısı 28'e düşürüldü. Özellikle içlerinde sadakatleri şüpheli olan bazı lejyonlar dağıtıldı. Bazıları Gemina (ikiz) unvanıyla birleştirildi.[1] Ayrıca Augustus göürnüşte İtalya'da barışı muhafaza edebilmek için dokuz özel cohortes oluşturdu ve bunların en azından üçünü Roma'da konuşlandırdı. Bu cohortes sonradan Praetorian muhafızları olarak bilinen birimler haline geldi.
Octavianus otokrasi ve krallığın Romalıların yüzyıllardır tecrübe etmedikleri ve sakındıkları şeyler olduğunun farkındaydı. Octavianus bir tiran olarak görülmek istemiyordu ve anayasal cumhuriyet yanılgısını korumaya çalıştı. Roma Cumhuriyeti anayasasını hâlâ işlevselmiş gibi göstermeye çalıştı. Gaddar Lucius Cornelius Sulla gibi geçmişteki Roma diktatörleri bile Roma'yı asla bir, iki seneden fazla olmamak üzere kısa süreliğine yönetmişti (Jül Sezar haricinde). MÖ 27'de Octavianus resmen tüm tüm yetkilerini Roma senatosuna bırakmaya çalıştı. Dikkatlice kurgulanmış bir şekilde o sırada büyük bölümü kendi taraftarları olan senatörler bu teklifi teddettiler ve Roma cumhuriyeti ve halkının iyiliği için yetkileri elinde tutmaya devam etmesi için yalvardılar. Anlatılana göre Octavianus'un konsüllükten çekileceği önerisi Roma'daki plebler arasında isyanlara neden olmuştu. Senato ve Octavianus arasında "Birinci Uzlaşma" olarak bilinen bir anlaşma sağlandı. Bu anlaşma Augustus'u halkın otokratı olarak meşrulaştırdı ve bir tiran olarak görülmeyeceğini temin ederek Pax Romana olarak bilinen uzun dönemin başlangıcı oldu.`

export default function (state = initialState, action) {
  switch (action.type) {
    case 'TEXT_CHANGED':
      return action.newText
  }
  return state
}
